/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.etctakip;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author frankie
 */
public class Egitimler extends javax.swing.JFrame {

    /**
     * Creates new form Egitimler
     */
    public Egitimler() {
        initComponents();
        fetchDataFromDatabase();
        fetchComboBoxCourseData();
        fetchComboBoxTutorData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Inconsolata Expanded Black", 0, 18)); // NOI18N
        jLabel1.setText("      Eğitimler");

        jLabel2.setText("Filtrele");

        jLabel5.setText("Eğitmen");

        jLabel6.setText("Kurs Adı");

        jButton1.setText("Filtrele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kurs", "Başlama Tarihi", "Bitiş Tarihi", "Kurs Saati", "Öğrenci Sayısı", "Eğitmen", "Aktiflik"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton3.setText("Eğitimi Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Yeni Eğitim");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Çık");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Güncelle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seç", "Genel İngilizce", "Konuşma", "YDS", "YÖKDİL", "IELTS", "TOEFL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seç" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Sıfırla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("aktif/inaktif");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 138, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))))
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton5)
                                .addGap(70, 70, 70))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel2)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(656, 656, 656))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(jButton4)
                                .addComponent(jButton5)
                                .addComponent(jButton6)
                                .addComponent(jButton7)))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        YeniEgitim yeniEgitim = new YeniEgitim();
        yeniEgitim.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Tüm satırları temizle
        fetchDataFromDatabase();
        jComboBox1.removeAllItems();
        fetchComboBoxCourseData();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String kursFilter = jComboBox1.getSelectedItem().toString();
        String egitmenFilter = jComboBox2.getSelectedItem().toString();

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter);

        List<RowFilter<Object,Object>> filters = new ArrayList<>();

        // Kurs filter
        if (!kursFilter.equals("seç")) {
            filters.add(RowFilter.regexFilter(kursFilter, 1)); // 1 is the index of kurs column
        }

        // Eğitmen filter
        if (!egitmenFilter.equals("seç")) {
            filters.add(RowFilter.regexFilter(egitmenFilter, 6)); // 6 is the index of egitmen column
        }


        RowFilter<Object,Object> combinedFilter = RowFilter.andFilter(filters);
        sorter.setRowFilter(combinedFilter);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        // jComboBox2 ve jComboBox3'ü "Seç" olarak ayarla
        jComboBox1.setSelectedItem("seç");
        jComboBox2.setSelectedItem("seç");

        // Veritabanından verileri alarak tabloyu güncelle
        jTable1.setRowSorter(null);
        //fetchDataFromDatabase();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Seçili satırın indeksini al
        String url = "jdbc:mysql://localhost:3306/etc_academy_ybs";
        String username = "root";
        String password = "etc5861";
        int selectedRowIndex = jTable1.getSelectedRow();

        // Seçili satırdaki eğitim ID'sini al
        int selectedEgitimID = Integer.parseInt(jTable1.getValueAt(selectedRowIndex, 0).toString());

        try {
            // Veritabanı bağlantısını oluştur
            Connection conn = DriverManager.getConnection(url, username, password);

            // PreparedStatement oluştur ve ödemeleri bulmak için sorguyu hazırla
            PreparedStatement findPaymentIdStmt = conn.prepareStatement("SELECT odeme_id FROM odeme_egitim_id WHERE egitim_id = ?");
            findPaymentIdStmt.setInt(1, selectedEgitimID);

            // Sorguyu çalıştır ve ödeme ID'lerini al
            ResultSet paymentIdResult = findPaymentIdStmt.executeQuery();
            while (paymentIdResult.next()) {
                int paymentID = paymentIdResult.getInt("odeme_id");

                // Billing tablosundan ödemeyi sil
                PreparedStatement deleteBillingStmt = conn.prepareStatement("DELETE FROM billing WHERE id = ?");
                deleteBillingStmt.setInt(1, paymentID);
                deleteBillingStmt.executeUpdate();
                
                PreparedStatement deleteOdemeEgitimStmt = conn.prepareStatement("DELETE FROM odeme_egitim_id WHERE odeme_id = ?");
                deleteOdemeEgitimStmt.setInt(1, paymentID);
                deleteOdemeEgitimStmt.executeUpdate();
            }

            // Diğer tablolardan ilgili satırları sil
            PreparedStatement deleteEgitimStmt = conn.prepareStatement("DELETE FROM egitim_etc WHERE id = ?");
            deleteEgitimStmt.setInt(1, selectedEgitimID);
            deleteEgitimStmt.executeUpdate();

            PreparedStatement deleteEgitmenStmt = conn.prepareStatement("DELETE FROM egitim_egitmen_id WHERE egitim_id = ?");
            deleteEgitmenStmt.setInt(1, selectedEgitimID);
            deleteEgitmenStmt.executeUpdate();

            PreparedStatement deleteOgrenciStmt = conn.prepareStatement("DELETE FROM egitim_ogrenci_id WHERE course_id = ?");
            deleteOgrenciStmt.setInt(1, selectedEgitimID);
            deleteOgrenciStmt.executeUpdate();

            // Bağlantıyı kapat
            conn.close();

            // jTable1'i güncelle
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Tüm satırları temizle
            fetchDataFromDatabase(); // jTable1 için verileri yeniden yükle
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Seçili satırın indeksini al
        String url = "jdbc:mysql://localhost:3306/etc_academy_ybs";
        String username = "root";
        String password = "etc5861";
        
        // Seçili satırın indeksini al
        int selectedRowIndex = jTable1.getSelectedRow();

        // Seçili satırdaki eğitim ID'sini al
        int selectedEgitimID = Integer.parseInt(jTable1.getValueAt(selectedRowIndex, 0).toString());

        try {
            // Veritabanı bağlantısını oluştur
            Connection conn = DriverManager.getConnection(url, username, password);

            // Eğitimin mevcut durumunu al
            PreparedStatement getAktifStmt = conn.prepareStatement("SELECT aktif FROM egitim_etc WHERE id = ?");
            getAktifStmt.setInt(1, selectedEgitimID);
            ResultSet aktifResult = getAktifStmt.executeQuery();
            if (aktifResult.next()) {
                String currentStatus = aktifResult.getString("aktif");

                // Durumu tersine çevir
                String newStatus = currentStatus.equals("aktif") ? "inaktif" : "aktif";

                // Durumu güncelle
                PreparedStatement updateStatusStmt = conn.prepareStatement("UPDATE egitim_etc SET aktif = ? WHERE id = ?");
                updateStatusStmt.setString(1, newStatus);
                updateStatusStmt.setInt(2, selectedEgitimID);
                updateStatusStmt.executeUpdate();
            }

            // Bağlantıyı kapat
            conn.close();

            // jTable1'i güncelle
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Tüm satırları temizle
            fetchDataFromDatabase(); // jTable1 için verileri yeniden yükle
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void fetchDataFromDatabase() {
        String url = "jdbc:mysql://localhost:3306/etc_academy_ybs";
        String username = "root";
        String password = "etc5861";
        String query = "SELECT egitim_etc.id, CONCAT(egitim_etc.kind, ' - ', egitim_etc.donem) AS kurs, egitim_etc.baslama_tarihi, egitim_etc.bitis_tarihi, egitim_etc.kurs_saati, COUNT(egitim_ogrenci_id.course_id) AS ogrencisayisi, egitmen_etc.adi, egitim_etc.aktif " +
                       "FROM egitim_etc " +
                       "INNER JOIN egitim_egitmen_id ON egitim_etc.id = egitim_egitmen_id.egitim_id " +
                       "INNER JOIN egitmen_etc ON egitim_egitmen_id.egitmen_id = egitmen_etc.id " +
                       "LEFT JOIN egitim_ogrenci_id ON egitim_etc.id = egitim_ogrenci_id.course_id " +
                       "GROUP BY egitim_etc.id";

        try (Connection connection = DriverManager.getConnection(url, username, password);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query)) {

           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

           // Tarih formatını belirle
           SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY/MM/dd");

           while (resultSet.next()) {
               java.sql.Date baslamaTarihi = resultSet.getDate("baslama_tarihi");
               java.sql.Date bitisTarihi = resultSet.getDate("bitis_tarihi");

               // Belirli bir biçime dönüştür
               String baslamaTarihiStr = dateFormat.format(baslamaTarihi);
               String bitisTarihiStr = dateFormat.format(bitisTarihi);

               Object[] rowData = {
                   resultSet.getInt("id"),
                   resultSet.getObject("kurs"),
                   baslamaTarihiStr,
                   bitisTarihiStr,
                   resultSet.getObject("kurs_saati"),
                   resultSet.getObject("ogrencisayisi"),
                   resultSet.getObject("adi"),
                   resultSet.getObject("aktif")
               };
               model.addRow(rowData);
           }
       } catch (SQLException e) {
           e.printStackTrace();
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Egitimler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Egitimler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Egitimler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egitimler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Egitimler().setVisible(true);
            }
        });
    }
    private void fetchComboBoxCourseData() {
    // Özel kursları ekle
        jComboBox1.addItem("seç");
        jComboBox1.addItem("Genel İngilizce");
        jComboBox1.addItem("Konuşma");
        jComboBox1.addItem("YÖKDİL");
        jComboBox1.addItem("YDS");
        jComboBox1.addItem("IELTS");
        jComboBox1.addItem("TOEFL");

        // Veritabanından gelen verileri ekle
        String url = "jdbc:mysql://localhost:3306/etc_academy_ybs";
        String username = "root";
        String password = "etc5861";
        String query = "SELECT CONCAT(kind, ' - ', donem) AS course FROM egitim_etc";

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(query)) {

            // Veritabanından gelen verileri ComboBox'a ekle
            while (resultSet.next()) {
                String course = resultSet.getString("course");
                jComboBox1.addItem(course);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void fetchComboBoxTutorData() {
    // Özel kursları ekle
       
        // Veritabanından gelen verileri ekle
        String url = "jdbc:mysql://localhost:3306/etc_academy_ybs";
        String username = "root";
        String password = "etc5861";
        String query = "SELECT adi FROM egitmen_etc";

        try (Connection connection = DriverManager.getConnection(url, username, password);
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(query)) {

            // Veritabanından gelen verileri ComboBox'a ekle
            while (resultSet.next()) {
                String course = resultSet.getString("adi");
                jComboBox2.addItem(course);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
